# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ae87fc8a634ca913645a8a0b95d0f25416c40d788ae3b1f9fb71beec347d3341b094ca03952eb82221f0d7443ba9651f70d69b510f344f1a45b5733e117a31

test:
  secret_key_base: 35a3235512c29389e4bc196457b0546d864c9e62d5c11bfe6082a6c2a69f94bb6fb79abcc8ae84ee8af3ba12c809a59bc520a32daeeebe1f4896a0432904df37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
